### ISSUE TITLE
Lcov throwing Error: Missing sourcemap:

### ISSUE THREAD

**Issue by joerideg** [Tapad/lcov-sourcemap#3]
Hi guys,

I am trying to use your library to remap my produced coverage results of karma-coverage back to their original source files.

Unfortunately it keeps throwing this error and I cant seem to figure out why. I have setup a super simple example project [here](https://github.com/onehippo/hippo-ngbp/tree/lcov-sourcemap)

I hope you can point me in the right direction!

**Comment by jessezhang91** [comment]
Hmm, it seems the sourcemaps generated don't have a sourceRoot. I'm trying to make some changes that hopefully will be able to handle this case.

**Comment by jessezhang91** [comment]
I think 94d315bd73b7fe1bcb78f5ee1596c2f6e70d6be2 should fix this. Let me know if there are any other issues. Closing for now. Thanks!

**Comment by joerideg** [comment]
Thanks! Seems to work!
