### ISSUE TITLE
Absolutely specified file:/// paths become relative after translation

### ISSUE THREAD

**Issue by Pablissimo** [Tapad/lcov-sourcemap#4]
Think this is a side-effect of the webpack support (https://github.com/Tapad/lcov-sourcemap/blob/master/lib/index.js#L34) - if you have a file specified by a ./-prefixed file URI in the source LCOV file:

    ./file:///home/user/file.ts

the code above strips all three slashes after the file specifier, resulting in a relative path being output

    home/user/file.ts

with the below being expected:

    /home/user/file.ts

Attached ZIP has an example ````lcov.info```` that gets translated into ````lcov.dat```` via ````run.js.map````, all of which are parts of output from building and testing the TypeScript compiler. Entirely possible I'm screwing up the usage of lcov-sourcemap (had to specify the source folder as / to get it to work at all) so apologies if so. May also be a problem in one of the tools generating the LCOV or map files.

[absolute-path-oddities.zip](https://github.com/Tapad/lcov-sourcemap/files/192374/absolute-path-oddities.zip)

OS Ubuntu 14.04 LTS (doesn't happen on Windows, possibly due to the various paths being differently-specified), lcov-sourcemap 0.3.0.

**Comment by jessezhang91** [comment]
You're right. I think the regex is too aggressive. I'll patch it to handle the file:// properly. I'll have to play around with other bundlers a bit more to understand how those sourcemaps are written. I'll try to get this in later today or tomorrow.

Also, what bundler do you use to generate the sourcemaps? I'm trying to put together something so I can test this package properly.

**Comment by Pablissimo** [comment]
It's the advertised build process for [TypeScript](https://github.com/Microsoft/TypeScript), so probably it's ````tsc```` that's doing the bundle and map generation - then Istanbul against Mocha for the LCOV output.

Quickest way is probably the following:
````
git clone https://github.com/Microsoft/TypeScript.git
cd TypeScript
npm install -g jake
npm install
jake clean && jake install
jake build-rules
jake generate-code-coverage
````

Output on the back of that is (amongst other things):

- ````TypeScript/coverage/lcov.info````
- ````TypeScript/built/local/run.js.map````

**Comment by jessezhang91** [comment]
Cool, thanks! I'm planning on doing a rewrite to make this library "safer" to use since there are so many different ways to bundle things.

I've pushed up a change to master (4212b38) that should address the `./file://` issue and hopefully will keep the webpack change intact. Let me know if this works and I'll publish it as 0.3.1. Thanks!

**Comment by Pablissimo** [comment]
Will give it a bash tonight and let you know! Thanks for responsiveness, only using the tool on a little side-project but suspect I'll find more uses for it soon

**Comment by Pablissimo** [comment]
Seems to do the trick! Absolutely specified paths now coming out as absolute after translation, nice one.

**Comment by jessezhang91** [comment]
Great, thanks!
